### ISSUE TITLE
Fix the news card sizing, and instead of using a loader, I added animate-pulse.

### ISSUE THREAD

**Issue by AjitGode** [happyrao78/Hunar#10]
I have fixed the news cards to have the same size, with uniform spacing and layout.
Also I have changes news card will show a pulsing placeholder for the image, text, and button while loading.
Once the news data is fetched, the actual content (image, title, and button) will replace the placeholders.
This gives a more realistic skeleton screen effect while the news is loading, improving the user experience.

Before : 

https://github.com/user-attachments/assets/6bd21593-bc35-4e97-bf66-e623f1907c72

After:

https://github.com/user-attachments/assets/c0f3bfc9-9cf3-4b21-a6b8-094a32f9f684

**Comment by happyrao78** [comment]
Create the Pull request for this. @AjitGode
