### ISSUE TITLE
Added Contact Form Validation

### ISSUE THREAD

**Issue by AjitGode** [happyrao78/Hunar#9]
Added conditional styling for the result message to visually indicate success (green) or error (red) , also added isLoading state to show "Sending..." on the button while the form is submitting and to disable the button to prevent multiple submissions.

https://github.com/user-attachments/assets/46aa8e41-75a2-45ad-aaac-b5f5b6f8df1a

**Comment by happyrao78** [comment]
Create the PR for this @AjitGode
